#!/bin/bash

set -e

export ZKHOST="${ZKHOST:-"${ZK_PORT_2181_TCP#tcp://}"}"

if [[ -z $ZKHOST ]]; then
  echo 'No ZooKeeper host is configured. Set ZKHOST or link a container using the name `zk`'
  exit 1
fi

export CLASSPATH="$SOLR_WEBAPP_DIR/solr-webapp/WEB-INF/lib/*:$SOLR_WEBAPP_DIR/lib/ext/*"
export _JAVA_OPTIONS="$_JAVA_OPTIONS -Dlog4j.configuration=file:$SOLR_WEBAPP_DIR/scripts/cloud-scripts/log4j.properties"

java org.apache.solr.cloud.ZkCLI --zkhost "$ZKHOST" $@
